ALTER TABLE PROJECT ADD SECTION_LEADER INTEGER;
ALTER TABLE PROJECT ADD HEAD_OF_UNIT INTEGER;
ALTER TABLE PROJECT ADD CONTRACT_MANAGER INTEGER;

ALTER TABLE PROJECT ADD FOREIGN KEY (SECTION_LEADER) REFERENCES USERS(USER_ID);
ALTER TABLE PROJECT ADD FOREIGN KEY (HEAD_OF_UNIT) REFERENCES USERS(USER_ID);
ALTER TABLE PROJECT ADD FOREIGN KEY (CONTRACT_MANAGER) REFERENCES USERS(USER_ID);